apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test-operator
  template:
    metadata:
      labels:
        name: test-operator
    spec:
      serviceAccountName: test-operator
      imagePullSecrets:
        - name: dockerauth
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: images.osrsmillionaires.tk/test-operator
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: images.osrsmillionaires.tk/test-operator
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "test-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
